algolia/algoliasearch-wordpress

docs/layouts/home.html, docs/layouts/page.html, docs/src/sass/app.scss, docs/src/sass/components/_header.scss, docs/src/sass/settings/_settings.scss
=> docs(website): beta banner

docs/helpers/activeNav.js, docs/index.js, docs/layouts/home.html, docs/layouts/page.html, docs/package.json, docs/partials/footer.html, docs/partials/head.html, docs/src/index.md
=> Extract docs header and footer in partials

wordpress/wp-content/plugins/algolia/LICENSE.txt, wordpress/wp-content/plugins/algolia/README.txt, wordpress/wp-content/plugins/algolia/algolia.php, wordpress/wp-content/plugins/algolia/index.php, wordpress/wp-content/plugins/algolia/uninstall.php
I think the `.gitignore` didn't add those files.
=> chore(release): missing files

wordpress/wp-content/plugins/algolia/admin/class-algolia-admin-page-logs.php, wordpress/wp-content/plugins/algolia/includes/class-algolia-logger.php
=> Log errors even if logging is disabled

wordpress/wp-content/plugins/algolia/admin/class-algolia-admin-page-autocomplete.php
=> Add a notice when we detect that autocomplete config is wrong

wordpress/wp-content/plugins/algolia/admin/class-algolia-admin-page-native-search.php
=> Display admin notice if we detect wrong native search configuration

README.md, wordpress/wp-content/plugins/algolia/README.txt
=> Add instructions to create new release

docs/src/customize-autocomplete.md, wordpress/wp-content/plugins/algolia/public/css/algolia-autocomplete.css, wordpress/wp-content/plugins/algolia/public/js/algolia-public-autocomplete.js, wordpress/wp-content/plugins/algolia/public/partials/algolia-autocomplete-post-suggestion.php, wordpress/wp-content/plugins/algolia/public/partials/algolia-autocomplete-user-suggestion.php
- make sure the dropdown width fits the input width
- display the snippeted content by default
- CSS cleanup
=> feat(autocomplete): dropdown menu improvements

docs/partials/footer.html
=> Only load search if search input is available in the page

wordpress/wp-content/plugins/algolia/includes/indices/class-algolia-posts-index.php, wordpress/wp-content/plugins/algolia/includes/indices/class-algolia-searchable-posts-index.php
=> Add username to post records by default

CHANGELOG.md, algolia.php, docs/index.js, package.json
=> Bump version to 0.3.0

docs/layouts/page.html, docs/src/wpml.md, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
=> Make sure we remove all query filters when indexing posts

includes/indices/class-algolia-posts-index.php
This is useful when implementing the hierarchical menu widget of instantsearch.js
=> Add category_tree attribute

docs/src/extend-basics.md, docs/src/instantsearch.md, docs/src/synonyms.md
=> Multiple docs improvements

assets/css/algolia-instantsearch.css, templates/instantsearch.php
Make use of the new `facetingAfterDistinct` to display correct facet counts.
Resolves: #149
Thank you @speedblue !!!
=> Display correct facet counts

includes/class-algolia-api.php
=> Gracefully handle missing API Client requirements

assets/css/algolia-instantsearch.css
=> Remove input shadow for instantsearch

assets/js/frontend/autocomplete.js
Addresses: #172
/cc @ethansmith
=> Make sure we size the dropdown as it is first opened

classmap.php, includes/indices/class-algolia-index-replica.php, includes/indices/class-algolia-index.php, includes/indices/class-algolia-posts-index.php
Resolves: #148
We still need to:
=> Support index replicas

includes/admin/class-algolia-admin.php
=> Add a notice in admin UI if mbregex is disabled

README.txt
=> Readme review

includes/class-algolia-plugin.php
`SCRIPT_DEBUG` force to use dev version of JavaScript. Read more: https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG
=> Allow SCRIPT_DEBUG

includes/class-algolia-task-queue.php, includes/indices/class-algolia-index.php, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php, includes/indices/class-algolia-terms-index.php, includes/indices/class-algolia-users-index.php, includes/watchers/class-algolia-term-changes-watcher.php
Resolves: #229
This addresses the issue discovered by @Mamaduka
Basically here are the issues that this fixes:
- Delete user records from Algolia,
- Delete term records from Algolia,
Also, this now works around the fact that potentially the underlying post, user, term might no longer exist. Until this fix, it would raise an Exception, and the record would not be removed from Algolia.
=> Fix the removal of records from Algolia

includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
=> Push urls of all thumbnail sizes

includes/class-algolia-plugin.php
=> Make sure template loader is only loaded if API is reachable

classmap.php, docs/src/customize-autocomplete.md, docs/src/customize-search-page.md, includes/class-algolia-utils.php, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php, templates/autocomplete.php, templates/instantsearch.php
=> Push custom taxonomies to Algolia by default

assets/css/algolia-instantsearch.css, includes/admin/class-algolia-admin-page-settings.php, includes/class-algolia-settings.php, includes/class-algolia-template-loader.php, templates/autocomplete.php, templates/instantsearch.php
=> Add an option to disable Algolia powered by link

includes/admin/class-algolia-admin-page-settings.php, includes/class-algolia-settings.php
No longer display te removal of powered by in the UI. Allow to use a simple constant instead.
/cc @redox @Shipow
=> Allow to hide powered by with a constant

includes/class-algolia-task.php
=> Ensure that task post type is algolia_task

includes/admin/class-algolia-admin-page-autocomplete.php, includes/admin/class-algolia-admin-page-settings.php
=> Rank menu entry lower in admin

templates/autocomplete.php
=> Do not escape autocomplete headers

docs/src/installation.md, docs/src/sass/components/_docs.scss
=> Add a notice about password protection conflicting with queue handling

docs/src/frequently-asked-questions.md
=> Add Q&A about required wp_footer in theme templates

includes/admin/class-algolia-admin.php, includes/class-algolia-task-queue-loopback-async.php
=> Add support for a new constant that allows forcing HTTP in loopback

docs/layouts/home.html, docs/src/sass/components/_buttons.scss, docs/src/sass/components/_community.scss
Cherry picked interesting changes
=> Few tweaks for smaller screen

docs/layouts/home.html, docs/src/sass/app.scss, docs/src/sass/components/_buttons.scss, docs/src/sass/components/_community.scss, docs/src/sass/components/_header.scss, docs/src/sass/settings/_settings.scss
=> Docs reponsive fixes

includes/libraries/algoliasearch-client-php/README.md, includes/libraries/php-dom-parser/lib/simple_html_dom.php
=> Update PHP dependencies

includes/admin/class-algolia-admin.php, includes/class-algolia-logger.php, includes/class-algolia-task-queue-loopback-async.php
=> Allow redirections in loopback & limit log entries

docs/layouts/page.html, docs/src/migration.md, includes/admin/class-algolia-admin-page-indexing.php, languages/algolia.pot
=> Document migration best practices

docs/layouts/page.html, docs/src/customize-templates.md, docs/src/filters.md, includes/class-algolia-template-loader.php
Shipped with a guide about customizing the templates from a theme author point of view.
Resolves: #326
=> Add a way to provide custom template locations

algolia.php, includes/class-algolia-cli.php, includes/class-algolia-plugin.php, includes/class-algolia-task.php
Add support for WP_CLI commands:
* process-queue
* re-index-all
See: #252
=> Add WP-CLI process-queue command

docs/src/constants.md, includes/admin/class-algolia-admin-page-autocomplete.php, includes/admin/class-algolia-admin-page-indexing.php, includes/admin/class-algolia-admin-page-native-search.php
=> Introduce a constant to hide admin help notices

composer.json, package.json
Format ref: 
- https://docs.npmjs.com/files/package.json
- https://getcomposer.org/doc/04-schema.md#license
=> Update license in composer/package.json, add GPL-2.0

classmap.php, docs/src/installation.md, includes/admin/class-algolia-admin-page-indexing.php, includes/admin/class-algolia-admin.php, includes/admin/class-algolia-cache-helper.php, includes/class-algolia-cli.php, includes/class-algolia-task-queue.php, includes/class-algolia-task.php, templates/autocomplete.php, templates/instantsearch.php
It looks like we are still running into issues with transients having an expiration set.
http://wordpress.stackexchange.com/questions/108287/trouble-with-transient-api-when-w3tc-is-activated
=> Make the plugin play nicely with W3TC and other catching plugins

docs/helpers/marketing.js
=> Add Kissmetrics tracking

includes/class-algolia-search.php
Adding filter `algolia_search_params` to allow changes before to search in Algolia.
This would allow us to add custom attributes to the search params.
=> Add filter algolia_search_params

docs/src/filters.md
=> Add new algolia_search_params to the docs

docs/layouts/home.html
Please do not merge, waiting for approval.
=> Subscribe users to WooCommerce list on landing page

includes/admin/class-algolia-admin-page-settings.php
=> Display exception message when API call fails during login

includes/indices/class-algolia-index.php
=> Sanitize data before it is json encoded by the Algolia API Client

docs/src/constants.md
So that preview doesn't fail on github
=> Format table in constants.md

includes/indices/class-algolia-index.php
=> Avoid logging the batch of records when re-indexing

includes/admin/class-algolia-admin-page-settings.php, includes/class-algolia-api.php
=> Allow user generated admin API keys

docs/src/filters.md, docs/src/frequently-asked-questions.md, docs/src/installation.md, includes/admin/class-algolia-admin.php, includes/class-algolia-task-queue-loopback-async.php
This is mainly introduced to fix #385
=> Introduce a filter to override loopback calls

docs/index.js, docs/layouts/page.html, docs/partials/footer.html, docs/src/js/app.js
* Move vendor dir to deps because GH now ignores vendor dir by default
* Make sure we don't reference twitter code if not applicable
=> Fix several documentation issues

docs/layouts/page.html, docs/src/wp-cli.md
=> Document WP-CLI commands

docs/src/frequently-asked-questions.md
=> Document removal of non-useful thumbnail sizes

includes/indices/class-algolia-posts-index.php
=> More resilient way of getting the admin index name

includes/indices/class-algolia-index.php
=> Allow master indices to be moved

README.txt, docs/src/installation.md
=> Be more transparent about pricing

docs/src/constants.md, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
=> Limit the size of the content attribute to 5000 bytes

includes/class-algolia-api.php, includes/indices/class-algolia-searchable-posts-index.php
This was moved to Algolia_Utils
=> Remove duplicated method and add a filter to hook into UA

includes/class-algolia-template-loader.php
Useful for pre-setting the current query.
=> Add current query to js algolia variable

docs/src/constants.md, docs/src/migration.md, includes/admin/class-algolia-admin-page-indexing.php, includes/admin/class-algolia-admin-page-settings.php, includes/class-algolia-settings.php
=> Introduce constants to ease env switching

includes/indices/class-algolia-index.php
=> Avoid clearing synonyms on re-index

includes/class-algolia-settings.php
=> Fix the condition for disabling the powered by branding

docs/src/logs.md
=> Recommend an extension to access PHP error logs

docs/src/sass/settings/_settings.scss
not every computer loads remote fonts or has helvetica :smile:
=> add sans-serif as last-resort fallback font

includes/class-algolia-plugin.php, includes/class-algolia-template-loader.php
This makes sure it it always loaded before usage in inline scripts.
Resolves: #480
=> Make wp-util a dependency of tha algolia client

includes/class-algolia-compatibility.php
=> Apply YOAST SEO frontend optimizations when generating records

includes/libraries/php-dom-parser/CHANGELOG.md, includes/libraries/php-dom-parser/lib/simple_html_dom.php
=> fix(simply-dom-html): do not try to load content from file

docs/index.js, docs/package.json, docs/src/frequently-asked-questions.md, docs/src/js/app.js, docs/src/sass/app.scss
Waiting for #523 to be resolved.
=> Add instructions on how to remove powered by logo

docs/package.json
=> upgrade header

docs/package.json
Updated component - fixes for header link + some minor details
=> automatic update of algolia components

docs/component_data/communityHeader.json, docs/package.json
@rayrutjes I made a better prioritisation in the community dropdown so we better link between our integration families.
=> better prioritisation

includes/class-algolia-compatibility.php
=> fix(polylang): don't conflict with polylang

includes/indices/class-algolia-posts-index.php
=> fix(indexing): restore behaviour of un-splitted records

includes/admin/class-algolia-admin.php, includes/admin/js/push-settings-button.js, includes/admin/partials/page-autocomplete-config.php, includes/admin/partials/page-search.php, includes/indices/class-algolia-index.php
=> feat(admin): add buttons to re-push the settings

docs/src/frequently-asked-questions.md
=> docs(faq): explain how to push custom thumbnail sizes

includes/class-algolia-autocomplete-config.php, includes/indices/class-algolia-searchable-posts-index.php
=> feat(autocomplete): allow to use the same index as on the search page

includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
=> fix(indexing): send un-escaped content to Algolia

includes/admin/class-algolia-admin-page-settings.php
=> fix(admin): properly handle configuration in constants

includes/watchers/class-algolia-post-changes-watcher.php, includes/watchers/class-algolia-term-changes-watcher.php, includes/watchers/class-algolia-user-changes-watcher.php
=> fix(indexing): avoid throwing fatal error in admin

includes/admin/class-algolia-admin.php
This will now discard any content outputted by plugins during content retrieval.
=> feat(indexing): trap content outputted by plugins

docs/src/customize-templates.md
Two links were not formatted as links.
=> Fixed link formatting

docs/src/filters.md, docs/src/indexing-flow.md, includes/class-algolia-plugin.php
=> feat(indexing): introduce a way to filter indexed searchable post types

docs/src/custom-attributes.md
=> docs(custom-attribute): update docs to reflect new version of the plugin

includes/indices/class-algolia-terms-index.php
=> fix(indexing): send unescaped terms to Algolia

includes/class-algolia-search.php
=> refactor(backend-search): simplify WP_Query hooking

includes/class-algolia-api.php
=> fix(admin): be more permissive on search API key validation

includes/indices/class-algolia-index.php, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php, includes/indices/class-algolia-terms-index.php, includes/indices/class-algolia-users-index.php
=> Perf delete by

includes/indices/class-algolia-index.php, includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
=> fix: remove usage of deleteby to avoid delaying indexing

templates/autocomplete.php
=> fix(autocomplete): only escape suggestion attributes once

docs/src/wpml.md
=> docs(wpml): finalize the WPML guide

docs/layouts/home.html, docs/partials/head.html, docs/src/sass/app.scss
=> Landing page message sayong the project isn't supported any longer
