core/QueryReplacer.php
The "post search" field in the admin frontend will not return any results when the plugin is active. This pull request is a workaround to help us solve the problem.  
How to reproduce:
* Login to wordpress
* Click on Posts -> All Posts
* Search with "Search Posts" form in the upper right corner
=> Disable algolia search in admin backend

admin/views/admin_menu.php
Hi. While trying to integrate the Algolia plugin with custom post types, I saw that in the admin settings for Algolia, when adding a custom post type to autocomplete types, the custom post type name was being overwritten with what seems an accidental assignation.
Thanks!
=> Fixed post type overwriting when filtering product variations

templates/default/templates.php
I just corrected a small issue on the template files.
=> Missing #instant-search-results-container div close tag

wordpress/wp-content/plugins/algolia/admin/class-algolia-admin-page-autocomplete.php, wordpress/wp-content/plugins/algolia/admin/class-algolia-admin-page-native-search.php, wordpress/wp-content/plugins/algolia/admin/js/algolia-admin.js, wordpress/wp-content/plugins/algolia/admin/partials/page-autocomplete-config.php
* Ensure the "error" message is readable & displayed first instead of having it instead of the actual configuration input. (We might want to tune the CSS here, I used their default one).
* Display the inputs with `disabled` states
* Display the empty table
=> chore(configuration): improve the UX when no types have been configured

wordpress/wp-content/plugins/algolia/includes/class-algolia-plugin.php
By default WordPress recommends registering post types on the init hook.
Users tend to not provide the 3rd parameter which would result in it being assigned 10.
Here we simply load the indices at 20 instead of the default 10 to make sure we have all user registered post types.
Resolves: #122
=> Load indices after other post types are registered

wordpress/wp-content/plugins/algolia/includes/class-algolia-api.php
Now displays as:
```
Algolia for PHP 1.10.1; WordPress integration (0.2.6); PHP (5.6.22); WordPress (4.5.3)
```
Resolves: #130
=> Fix user agent

templates/instantsearch.php
This helps understanding why instantsearch does not work in the frontend.
WDYT @redox ?
=> Add a JS alert if the searchable posts index is not indexed

docs/layouts/page.html, docs/src/customization.md, docs/src/customize-autocomplete.md, docs/src/customize-search-page.md, includes/class-algolia-template-loader.php, includes/indices/class-algolia-index.php, templates/autocomplete.php, templates/instantsearch.php
- Improved customization documentation (fix #171, fix #144)
- Cleanup autocomplete.js JS code (header, footer templates shouldn't be set from the
backend; here and there simplification)
- Replace the Hogan.js based templating (used in instantsearch.js) by Wordpress's underscore
one. Too complex to work with both.
=> Customization doc & review

includes/admin/class-algolia-admin-page-native-search.php
By scoping the notice to the actual Search Page in the admin, we allow users to use the instantsearch.php over loading mechanism, without being forced to use the searchable posts index.
Before this, if you decided to use a different index for instantsearch.php then you would be spammed by an error on every admin page.
=> Scope search page admin notice to the page

includes/admin/class-algolia-admin-page-indexing.php, includes/admin/css/algolia-admin.css, includes/admin/js/algolia-admin-indexing.js, includes/admin/partials/page-indexing.php, includes/class-algolia-task-queue.php, includes/class-algolia-task.php, languages/algolia.pot
* Re-designed the queue monitoring section
* Add a way to manually stop the queue
* No longer trash failing tasks but stop the queue instead
* Add a button for deleting all pending tasks
Resolves: #129, #341, #157
=> Add controls to the queue and improve monitoring display

docs/index.js, docs/package.json
Brings down the total size of the page from 1.8M to 600kb.
/cc @Shipow
=> Reduce landing page size by optimizing images

includes/indices/class-algolia-posts-index.php, includes/indices/class-algolia-searchable-posts-index.php
This allows shortcodes to be parsed in excerpts.
This better addresses the formatting issue than #383
=> Ensure excerpt are formatted properly

includes/admin/class-algolia-admin-page-indexing.php
This ensures user can easily setup different environments with different prefixes without
lossing already used indices each time.
Resolves: #442, #433
=> Re-index indices instead of moving them

docs/layouts/page.html, docs/partials/footer.html
* foundation.js was loaded unminified (300k vs 160k)
* jQuery and foundation were loaded twice on /page because it was in the footer already
=> use minified version of deps and deduplicate

includes/watchers/class-algolia-post-changes-watcher.php
Add the delete_attachment hook in order to update index when an attachment is deleted
=> fix(indexing): remove attachments from index when deleted

README.md, README.txt
Last month WP.org introduced support for this [feature](https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/). Currently it just displays information on plugins page, but in future it will prevent users installing plugin, if they are running old PHP versions.
=> Add minimum required PHP version to READMEs

includes/class-algolia-template-loader.php
The query retrieved in the URL is potentially used as input value.
Escaping the HTML is not expected here as it makes the value unusable for that purpose.
In other places where used, the query is already escaped.
Closes: #734
=> fix: do not escape query passed to frontend

includes/watchers/class-algolia-post-changes-watcher.php
When adding custom shared_attributes with the algolia_searchable_post_shared_attributes filter for example, it can occur that these attributes aren't synced properly the first time the post is saved. We've seen this happen on attributes that are based on post_meta. 
In this PR I've added a filter which lets us change the meta keys on which an update is triggered.
=> Filter indexed meta keys before triggering a sync

includes/indices/class-algolia-posts-index.php
I recently find a bug when updating an media attachment that was not linked to a page or a post. Updating the attachment was making it disappear from the algolia indice. By digging the problem, I found that the following line of the function should_index_post() in the file includes/indicesclass-algolia-posts-index.php was causing the bug: $parent_post = get_post( $post->post_parent ).
In the case of an media attachment that is not linked to a page or a post, post->post_parent is equal to 0 and calling the function get_post() with a value of 0 will not return null as expected. Instead, the function will return the same post ID of the current post when it's not finding any result. This is why I suggest to change the line to: $parent_post = ( $post->post_parent ) ? get_post( …
=> Fix should_index_post()

classmap.php, docs/src/filters.md
This covers the issue raised in #781 to allow developers to filter the loading of the search client library.
=> added filter for algolia_should_require_search_client
